### ISSUE TITLE
UMA

### ISSUE THREAD

**Issue by bhack** [CNugteren/Claduc#11]
What do you think to handle CUDA UMA and some [OpenCL extension](https://developer.qualcomm.com/forum/qdn-forums/mobile-technologies/mobile-gaming-graphics-optimization-adreno/27145) for mobile or OpenCL 2.x SVM? /cc @beru @pansk @edgarriba

**Comment by bhack** [comment]
On mobile there is also clDeviceInfo  [HOST_UNIFIED_MEMORY](https://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/clGetDeviceInfo.html) that could be checked. I don't know if we could add this info on device creation so that we could handle memory transfer conditionally.

**Comment by Randl** [comment]
As for CUDA, new version (CUDA 8) brings very simple unified memory managment: https://devblogs.nvidia.com/parallelforall/cuda-8-features-revealed/ 

That is probably not true for OpenCL though

**Comment by bhack** [comment]
TF opinion was not so good. See https://github.com/tensorflow/tensorflow/issues/3678

**Comment by CNugteren** [comment]
I'll see what I can do. I welcome contributions though if anyone of you has the time and the experience. We will probably have to start thinking about what kind of interface you envision?

**Comment by bhack** [comment]
I'm less sure on Nvidia UMA side probably @pansk can give another opinion: http://stackoverflow.com/questions/21986542/is-cudamallocmanaged-slower-than-cudamalloc

**Comment by bhack** [comment]
For Opencl I think we need to try to see what kind of interface we could introduce for SVM and different mobile extension of 1.x series.

**Comment by bhack** [comment]
@CNugteren for mobile we could start from here. We always use nullPtr parameter at https://github.com/CNugteren/CLCudaAPI/blob/master/include/clpp11.h#L526. What do you think to have this conditional?

**Comment by bhack** [comment]
From qualcomm docs:

>  Zero memory copy (Avoiding memory copy) 
To avoid a hidden memory copy, use cl_mem_flags flag CL_MEM_ALLOC_HOST_PTR when 
creating a memory object with clCreateBuffer or clCreateImage. 
When mapping a buffer object or an image object to host memory space, use clEnqueueMapBuffer, 
clEnqueueMapImage and clEnqueueUnmapMemObject APIs.
Be aware that even with zero copy there is a cost to using Map/Unmap calls, because the driver has 
to flush or invalidate the CPU cache as required.
To avoid memory copy when sharing data between different external components and the GPU, 
use ION memory and the extension cl_ion_qcom_host_ptr. Alternatively, use Android native buffers 
and the extension cl_qcom_android_native_buffer_host_ptr to avoid memory copy. Android native 
buffers are based on ION.

**Comment by bhack** [comment]
See also similar on [Mali Sharing Data Across Devices](http://malideveloper.arm.com/downloads/deved/tutorial/SDK/opencl/memory_buffers_tutorial.html)

**Comment by pansk** [comment]
@bhack, I confirm what's on that SO link, and especially in the answer: "Today's implementation of Unified Memory and cudaMallocManaged will not be faster than intelligently written code written by a proficient CUDA programmer".

That probably still holds in CUDA 8, although there's something interesting in this version: You can now oversubscribe GPU memory (effectively allocating more memory than the amount physically present in the GPU) and have it paged in and out automatically from CPU memory. This allows a simpler design of your network: you don't really need to explicitly reason about where your data is, you just access it from CPU or GPU as you want. Of course, you pay for this "feature", but I would be surprised if in our specific use case (DNN) it would cost as much as in that benchmark (while training a GPU-only network, without oversubscription, I expect the layer-specific memory to be mapped on the GPU full time.

In addition, starting from CUDA 8 you can use hints (cudaMemAdvise) and explicit prefetching (cudaMemPrefetchAsync()) to obtain similar performance as manually-managed memory (http://on-demand.gputechconf.com/gtc/2016/presentation/s6216-nikolay-sakharnykh-future-unified-memory.pdf).

**Comment by bhack** [comment]
@pansk Ok I've adressed the Opencl 1.x piece of code where we need to impact here. Do you see some code section to impact here on CUDA version of the header?

**Comment by bhack** [comment]
The problem is also to maintain API abstraction compatibile with Opencl counterpart

**Comment by CNugteren** [comment]
I am sorry but I came to the conclusion that at this moment I don't have the time to work on this. My priority is with the [CLBlast library](https://github.com/CNugteren/CLBlast). I also don't have any specific knowledge about unified memory nor any useful test platforms (I guess?).

But I am happy to help out in the discussion and giving feedback on any pull request. The CLCudaAPI codebase is so simple (two files!) and small that it should be possible for anyone to contribute. I guess you could start with a `template <typename T> class BufferUMA` based on `clEnqueueMapBuffer` and such for OpenCL and then see where that'll get you?

**Comment by bhack** [comment]
If we are going to introduce BufferUMA we need to be aware of device type/sdk version at user level to be aware if we want or can istantiate this kind of new buffer.

**Comment by bhack** [comment]
@naibaf7 Are you handling this cases in Caffe relying on ViennaCL features?

**Comment by naibaf7** [comment]
@bhack No it is implemented with bare OpenCL programmed by Intel (@gongzg) and me, it can be found in syncedmem.cpp (https://github.com/naibaf7/caffe/blob/master/src/caffe/syncedmem.cpp).

**Comment by bhack** [comment]
Ok you are manually handing this with ZEROCOPY_SUPPORTED
