### ISSUE TITLE
Can i just use the interface of opencl ?

### ISSUE THREAD

**Issue by zhangqianhui** [CNugteren/Claduc#7]
Because i want to move the cnn for c++ 11  to android .

**Comment by CNugteren** [comment]
I am not sure what your question is, but perhaps this helps: CLCudaAPI has one interface, but two back-ends (CUDA and OpenCL). Of course you can just use the OpenCL back-end.

**Comment by zhangqianhui** [comment]
I just want to accelerate my android project according the Opencl.Do you know ?

**Comment by bhack** [comment]
Yes you can include only the cl header.

**Comment by zhangqianhui** [comment]
@bhack  thanks .

**Comment by bhack** [comment]
@edgarriba is working on Opencl Kernel for tiny if it is your topic.

**Comment by zhangqianhui** [comment]
@bhack Will tiny-cnn use Opencl instand of cuda?

**Comment by bhack** [comment]
I suggest you to close this and talk on https://github.com/tiny-dnn/tiny-dnn/issues/235
