### ISSUE TITLE
Platforms list

### ISSUE THREAD

**Issue by bhack** [CNugteren/Claduc#8]
Are you interested to extend the API a little bit to let retrieve the platforms list? https://github.com/CNugteren/CLCudaAPI/blob/master/include/clpp11.h#L135 /cc @edgarriba

**Comment by CNugteren** [comment]
Sure. I understand your request as a non-member function which returns an `std::vector<Platform>`. Am I right?

**Comment by bhack** [comment]
Yes

**Comment by CNugteren** [comment]
The function `std::vector<Platform> GetAllPlatforms()` is now implemented for the OpenCL and CUDA back-ends. It is currently in the `development` branch, but will be included in the next release.

**Comment by bhack** [comment]
Thank you!
